package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class CreateOnlineController {
	private Stage stage;
	private Scene scene;
	private Parent root;
	@FXML
	private Button Sendbtn;
	@FXML
	private TextField TextToSend;
	@FXML
	private Label TextRecieved;
	@FXML
	private TextField TextToSend1;

	// Event Listener on Button[#Sendbtn].onAction
	@FXML
	public void Sendbuttononaction(ActionEvent event) throws IOException {
		// TODO Autogenerated
		String msg = "Host-"+TextToSend.getText()+"-"+TextToSend1.getText();		
		//TextRecieved.setText(player.accessServer(msg));
		String resp;
		resp=Client.accessServer(msg);
		if(resp.equals("Created"))
		{
			Client.playerpseudo=TextToSend1.getText();
			Client.roomToJoin=TextToSend.getText();
			TextRecieved.setText(resp);
			root = FXMLLoader.load(getClass().getResource("WaitPage.fxml"));
			stage = (Stage)((Node)event.getSource()).getScene().getWindow();
			scene = new Scene(root);
			stage.setScene(scene);		
			stage.show();
		}
	}
}
