package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;
import java.io.IOException;
import javafx.event.ActionEvent;

public class OnlinePageController {
	private Stage stage;
	private Scene scene;
	private Parent root;
	@FXML
	private Button backCreatemenu;
	@FXML
	private Button createRoomButton;
	@FXML
	private Button joinRoomButton;

	// Event Listener on Button[#backCreatemenu].onAction
	@FXML
	public void BackCreatemenuOnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		
	}
	// Event Listener on Button[#createRoomButton].onAction
	@FXML
	public void CreateRoomButtonOnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		root = FXMLLoader.load(getClass().getResource("CreateOnlinePage.fxml"));
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);		
		stage.show();
	}
	// Event Listener on Button[#joinRoomButton].onAction
	@FXML
	public void JoinRoomButtonOnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
		root = FXMLLoader.load(getClass().getResource("JoinOnlinePage.fxml"));
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);		
		stage.show();
	}
}
