package application.SceneControllers;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import application.Ressourcen;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.Slider;

import javafx.scene.control.RadioButton;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class GameHostPageController implements Initializable{
	private Stage stage;
	private Scene scene;
	private Parent root;
	@FXML
	private TextField RoomNameTextField;
	@FXML
	private TextField PlayerNicknameTextField;
	@FXML
	private RadioButton TowPlayersRadioButton;
	@FXML
	private ToggleGroup NumberOfPlayers;
	@FXML
	private RadioButton threePlayersRadioButton;
	@FXML
	private RadioButton FourPlayersRadioButton;
	@FXML
	private Label SpeedLabel;
	@FXML
	private ImageView LevelImageView;
	@FXML
	private Button PreviousLevelButton;
	@FXML
	private Button NextLevelButton;
	@FXML
	private Label MapNumberLabel;
	@FXML
	private Button RunRoomButton;
	@FXML
	private Button GameHostBackButton;
	@FXML
	private Slider SpeedSlider;
	int counter;
	// Event Listener on TextField[#RoomNameTextField].onAction
	@FXML
	public void RoomNameTextField(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#PreviousLevelButton].onAction
	@FXML
	public void PreviousLevelButtonIsClicked(ActionEvent event) {
		// TODO Autogenerated
	 	   counter= (counter-1)%4;
    	   if(counter <0) 
    		 counter=3;
    	   LevelImageView.setImage(Ressourcen.IMAGES.MAP.getMap(counter));
	}
	// Event Listener on Button[#NextLevelButton].onAction
	@FXML
	public void NextLevelButtonIsClicked(ActionEvent event) {
		// TODO Autogenerated
	    counter= (counter +1)%4;
	    LevelImageView.setImage(Ressourcen.IMAGES.MAP.getMap(counter));
	}
	// Event Listener on Button[#RunRoomButton].onAction
	@FXML
	public void RunRoomButtonIsClicked(ActionEvent event) {
		// TODO Autogenerated
		this.SpeedLabel.setText("Quick");
	}
	// Event Listener on Button[#GameHostBackButton].onAction
	@FXML
	public void GameHostBackButtonIsClicked(ActionEvent event) throws IOException {
		// TODO Autogenerated
		root = FXMLLoader.load(getClass().getResource("../Scenes/OnlinePage.fxml"));
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on Slider[#SpeedSlider].onDragDetected
	@FXML
	public void SpeedSliderIsDraged(MouseEvent event) {
		// TODO Autogenerated
		switch((int)this.SpeedSlider.getValue()) 
		{
		case 2:
			this.SpeedLabel.setText("Quick");
			break;
		case 3:
			this.SpeedLabel.setText("Normal"); 
			break;
		case 4:
			this.SpeedLabel.setText("Long"); 
			break;
		}
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		counter=0;
		LevelImageView.setImage(Ressourcen.IMAGES.MAP.getMap(counter));
	}
}
