package application.SceneControllers;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

public class LandingPageController {
	private Stage stage;
	private Scene scene;
	private Parent root;
	@FXML
	private Button SinglePlayButton;
	@FXML
	private Button OnlineButton;
	@FXML
	private Button GuideButton;
	@FXML
	private Button ExitButton;

	// Event Listener on Button[#SinglePlayButton].onAction
	@FXML
	public void SinglePlayButtonIsKlicked(ActionEvent event) throws IOException {
		// TODO Autogenerated
		root = FXMLLoader.load(getClass().getResource("/application/Scenes/SinglePlayPanel.fxml"));
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on Button[#OnlineButton].onAction
	@FXML
	public void OnlineButtonIsKlicked(ActionEvent event) throws IOException {
		// TODO Autogenerated
		root = FXMLLoader.load(getClass().getResource("/application/Scenes/OnlinePage.fxml"));
		stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		scene = new Scene(root);
		stage.setScene(scene);
		stage.show();
	}
	// Event Listener on Button[#GuideButton].onAction
	@FXML
	public void GuideButtonIsKlicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#ExitButton].onAction
	@FXML
	public void ExitButtonIsKlicked(ActionEvent event) {
		// TODO Autogenerated
		System.exit(0);
	}
	
}
