package application.SceneControllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class SinglePlayPanelController {
	@FXML
	private Button RunRoomButton;
	@FXML
	private Button GameHostBackButton;
	@FXML
	private TextField PlayerNicknameTextField;

	// Event Listener on Button[#RunRoomButton].onAction
	@FXML
	public void RunRoomButtonIsClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#GameHostBackButton].onAction
	@FXML
	public void GameHostBackButtonIsClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
